# Generated by Django 5.2 on 2025-04-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeta', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
